### ISSUE TITLE
How do I store/query stuff in this octree?

### ISSUE THREAD

**Issue by trsh** [Dimev/lodtree#2]
Like points?

**Comment by Dimev** [comment]
> Non-goals
> Be a general-usage tree data structure for storing items at specific locations.

You can't. This crate is specifically made to help generating and storing chunks for terrain with chunked LOD not for general storage. 
I'm working on 0.2, which does come with a new function to get a chunk at a specific location, but it won't do what you want.

Instead you can try [this crate](https://crates.io/crates/octree), but it's likely not as fast as possible due to each node taking up 2 allocations.

If you want to make your own, [this stackoverflow post](https://stackoverflow.com/questions/41946007/efficient-and-well-explained-implementation-of-a-quadtree-for-2d-collision-det) is a pretty good starting point. It also explains a lot of the techniques I used here to make it efficient. (keeping the actual node size small and storing children contiguously in memory)

**Comment by trsh** [comment]
Thank you!
